spring.application.name=gestao-biblioteca

# Ativa o console do H2 caso queira usar em paralelo (opcional)
spring.h2.console.enabled=true

# ===================================================================
# CONFIGURAÇÃO DO BANCO DE DADOS (MySQL)
# ===================================================================
# Certifique-se se a sua porta é 3366 ou 3306
spring.datasource.url=jdbc:mysql://localhost:3366/gestao_biblioteca?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysqlPW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURAÇÃO DO JPA / HIBERNATE (Descomentado)
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect